# Generated by Django 4.2.7 on 2023-11-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.IntegerField(
                choices=[
                    (1, "Абитуриент"),
                    (2, "Студент"),
                    (3, "Куратор"),
                    (4, "Преподаватель"),
                ]
            ),
        ),
    ]
