# Generated by Django 4.2.7 on 2023-11-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="NONAME", max_length=30, verbose_name="Имя"),
        ),
        migrations.AddField(
            model_name="user",
            name="surname",
            field=models.CharField(
                default="NONAME", max_length=30, verbose_name="Фамилия"
            ),
        ),
    ]
