# Generated by Django 4.2.7 on 2023-11-08 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_group_students"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                (
                    "baseprofile_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="users.baseprofile",
                    ),
                ),
                ("groups", models.ManyToManyField(to="users.group")),
            ],
            bases=("users.baseprofile",),
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "baseprofile_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="users.baseprofile",
                    ),
                ),
                ("sex", models.BooleanField(choices=[(0, "Женский"), (1, "Мужской")])),
                ("certificate_number", models.CharField(max_length=50)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.group"
                    ),
                ),
            ],
            bases=("users.baseprofile",),
        ),
    ]
