# Generated by Django 4.2.7 on 2023-11-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_teacherprofile_studentprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={"verbose_name": "Группа", "verbose_name_plural": "Группаы"},
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="certificate_number",
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="study_period",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("groups", models.ManyToManyField(to="users.group")),
            ],
            options={
                "verbose_name": "Направление",
                "verbose_name_plural": "Направления",
            },
        ),
    ]
