# Generated by Django 4.2.7 on 2023-11-12 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_group_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="specialization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="users.specialization",
            ),
        ),
    ]
