# Generated by Django 4.2.7 on 2023-11-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_studentprofile_specialization"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="patronymic",
            field=models.CharField(
                default="Ноунеймович", max_length=30, verbose_name="Отчество"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                default="Ноунейм", max_length=30, verbose_name="Имя"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="surname",
            field=models.CharField(
                default="Ноунеймов", max_length=30, verbose_name="Фамилия"
            ),
        ),
    ]
