# Generated by Django 4.2.7 on 2023-11-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_user_patronymic_alter_user_name_alter_user_surname"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="quantity_of_visiting",
            field=models.IntegerField(default=0),
        ),
    ]
