# Generated by Django 4.2.7 on 2023-11-14 00:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_studentprofile_quantity_of_visiting"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={"verbose_name": "Группа", "verbose_name_plural": "Группы"},
        ),
    ]
