# Generated by Django 4.2.7 on 2023-11-14 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_alter_group_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentprofile",
            options={
                "verbose_name": "Профиль студента",
                "verbose_name_plural": "Профили студентов",
            },
        ),
        migrations.AlterModelOptions(
            name="teacherprofile",
            options={
                "verbose_name": "Профиль преподавателя",
                "verbose_name_plural": "Профили преподавателей",
            },
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Название группы"),
        ),
        migrations.AlterField(
            model_name="group",
            name="students",
            field=models.ManyToManyField(
                blank=True, to=settings.AUTH_USER_MODEL, verbose_name="Студенты группы"
            ),
        ),
        migrations.AlterField(
            model_name="specialization",
            name="groups",
            field=models.ManyToManyField(
                to="users.group", verbose_name="Группы направления"
            ),
        ),
        migrations.AlterField(
            model_name="specialization",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Название направления"),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="group",
            field=models.ForeignKey(
                help_text="К какой группе принадлежит",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.group",
                verbose_name="Группа",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="quantity_of_visiting",
            field=models.IntegerField(default=0, verbose_name="Количество посещений"),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="sex",
            field=models.BooleanField(
                choices=[(0, "Женский"), (1, "Мужской")], verbose_name="Пол"
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="specialization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="users.specialization",
                verbose_name="Направление",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="study_period",
            field=models.CharField(
                max_length=10, null=True, verbose_name="Срок обучения"
            ),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="groups",
            field=models.ManyToManyField(
                help_text="У каких групп ведёт", to="users.group", verbose_name="Группы"
            ),
        ),
    ]
